---
- name: Install Linux Filebeat
  hosts: provision

  tasks:
  - name: Download Filebeat
    become: yes
    apt:
      deb: "https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-5.6.16-amd64.deb"
  - name: Install Filebeat
    become: yes
    apt:
      name: filebeat
      state: present
      update_cache: yes